name: Build static contents and deploy to Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:

# GITHUB_TOKEN のパーミッションを設定し、GitHub Pages へのデプロイを許可します
permissions:
  contents: read
  pages: write
  id-token: write

# 1つの同時デプロイメントを可能にする
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # デプロイするだけなので，単一のデプロイジョブでよい．
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: "npm"
      - name: Install dependencies (= npm install)
        run: npm install
      - name: Build (= npm run build)
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with: # アップロード対象を指定．build結果はdistへ出力されるため．
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
